const MenuActionTypes = {
	FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
	FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
	FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',

	SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',

	ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
};

export default MenuActionTypes;