export const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SELECT_CURRENT_USER: 'SELECT_CURRENT_USER',

	SET_CHEF_SETTINGS: 'SET_CHEF_SETTINGS',
	SELECT_CHEF_SETTINGS: 'SELECT_CHEF_SETTINGS',

	SET_CHEF_PROFILE_IMG: 'SET_CHEF_PROFILE_IMG',
	SET_CHEF_DESCRIPTION: 'SET_CHEF_DESCRIPTION',

	SET_CHEF: 'SET_CHEF'
}