const OrdersTypes = {
	FETCH_ORDERS_START: 'FETCH_ORDERS_START',
	FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
	FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

	SET_ACTIVE_SECTION: 'SET_ACTIVE_SECTION',
	SET_ACTIVE_DISH_DETAILS: 'SET_ACTIVE_DISH_DETAILS',
	SET_ACTIVE_SECTION_ON_UPDATE: 'SET_ACTIVE_SECTION_ON_UPDATE',

	FETCH_ORDERS_DETAILS_START: 'FETCH_ORDERS_DETAILS_START',
	FETCH_ORDERS_DETAILS_SUCCESS: 'FETCH_ORDERS_DETAILS_SUCCESS',
	FETCH_ORDERS_DETAILS_FAILURE: 'FETCH_ORDERS_DETAILS_FAILURE',
};

export default OrdersTypes;